# Visualização Inicial
Notebook responsável pela visualização inicial dos dados em `/data/processed/expired_items_dataset_processed.csv`.

---
# 1. Importando Bibliotecas

Bibliotecas utilizadas para manipulação, visualização de dados e controle de avisos.

In [1]:
# bibliotecas

import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

---
# 2. Atribuindo a Base de Dados para DataFrame

In [2]:
# importando dataset

df = pd.read_csv(
    '../data/processed/expired_items_dataset_processed.csv'
)

---
# 3. Validação Final

Importante manter o arquivo de limpeza aberto nessa etapa para confirmar diferenças.

In [3]:
# covertendo novamente colunas para datetime

for col in ['DATA', 'VALIDADE']:
    df[col] = pd.to_datetime(df[col], format='%Y-%m-%d')

Colunas convertidas novamente para manipular os dados nesse notebook.

Conversão definitiva será feita em SQL.

In [4]:
# confirma dimensões 
df.shape

(28006, 6)

In [5]:
# retorna a qnts de valores unicos em cada coluna + lista o nome das colunas

df.nunique()

DATA           370
BANDEIRA         2
LOJA            23
QUANTIDADE     212
SETOR           18
VALIDADE      1588
dtype: int64

In [6]:
# verifica se há datas de validade maiores que data de vistoria

df[df['VALIDADE']>df['DATA']]

Empty DataFrame
Columns: [DATA, BANDEIRA, LOJA, QUANTIDADE, SETOR, VALIDADE]
Index: []

In [7]:
# confere visualmente se os dados apresentam problemas

df.head()

        DATA BANDEIRA  LOJA QUANTIDADE                   SETOR   VALIDADE
0 2022-01-03     JOAO    16          1  MERCEARIA COMPLEMENTAR 2021-10-20
1 2022-01-03     JOAO    16          4  MERCEARIA COMPLEMENTAR 2022-01-01
2 2022-01-03     JOAO    16          1  MERCEARIA COMPLEMENTAR 2021-12-01
3 2022-01-03     JOAO    16          2  MERCEARIA COMPLEMENTAR 2022-01-01
4 2022-01-03     JOAO    16          3  MERCEARIA COMPLEMENTAR 2021-04-30

Validações concluídas, nenhum erro identificado.

DataFrame consistente e pronto para visualizações.